import { ATHLETE_USER, ATHLETE_ID, EXERCISE_ID, buildSeed } from './fixtures.mjs'
const { createMockSupabase } = await import('./mock-supabase.mjs')
const { startVite, launchBrowser, APP_URL, MOCK_PORT } = await import('./harness.mjs')
const vite = await startVite(); const browser = await launchBrowser()
const seed = buildSeed()
const d = n => new Date(Date.now() - n * 864e5).toISOString()
seed.tables.exercise_logs = [[28, 75, 5], [21, 80, 5], [14, 82.5, 5], [7, 85, 5], [0, 90, 4]].map(([n, w, r], i) => ({ id: '00000000-0000-4000-8000-00000000010' + i, exercise_id: EXERCISE_ID, athlete_id: ATHLETE_ID, set_number: 1, weight: w, reps_completed: r, note: null, rpe_actual: null, rpe_planned: null, skipped: false, logged_at: d(n) }))
const mock = createMockSupabase(seed); await mock.listen(MOCK_PORT)
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage()
await page.goto(APP_URL)
await page.locator('#athlete-auth-email').fill(ATHLETE_USER.email)
await page.locator('#athlete-auth-password').fill(ATHLETE_USER.password)
await page.getByRole('button', { name: 'Log ind' }).click()
await page.getByText('Dagens pas', { exact: true }).waitFor()
await page.waitForTimeout(1500)
const o = 'outputs/1402/'
await page.screenshot({ path: o + 'dagens-pas-390.png' })
await page.getByText('Program', { exact: true }).last().click(); await page.waitForTimeout(1500)
await page.screenshot({ path: o + 'program-390.png', fullPage: true })
await page.getByText('Fremgang', { exact: true }).last().click(); await page.waitForTimeout(2000)
await page.screenshot({ path: o + 'fremgang-1rm-390.png', fullPage: true })
await browser.close(); await vite.stop(); await mock.close()
